### ISSUE TITLE
Failed to solve release dependency certifi

### ISSUE THREAD

**Issue by Kozlov-V** [certifi/erlang-certifi#1]
I'm migrate my web-app to Cowboy 2.0 and Erlang 18.1
But i have problem with solve release when i add Certifi app to my_application.app.src file
```
{application, testcowboy, [
  {description, "Hello Erlang!"},
  {vsn, "0.1.0"},
  {modules, []},
  {registered, [testcowboy]},
  {applications, [
    kernel,
    stdlib,
    eredis,
    certifi,
    cowboy
  ]},
  {mod, {testcowboy_app, []}},
  {env, []}
]}.
```

When i do ```make``` i have this error:
```
APP    testcowboy.app.src
 GEN    distclean-relx-rel
===> Starting relx build process ...
===> Resolving OTP Applications from directories:
          /Users/asup/Documents/Develop/Erlang/testcowboy/ebin
          /Users/asup/Documents/Develop/Erlang/testcowboy/deps
          /usr/local/lib/erlang/lib
          /Users/asup/Documents/Develop/Erlang/testcowboy/apps
Failed to solve release:
 Dependency certifi is specified as a dependency but is not reachable by the system.
```
How i can use Certifi?
Thank you!

**Comment by benoitc** [comment]
it should be added to erlang.mk will do a PR for that. Thanks to have noticed it.

**Comment by benoitc** [comment]
alternatively you can add it to your deps in your makefile.

**Comment by Kozlov-V** [comment]
I tried to make these two ways:
1.  Add it to my deps in my app makefile:
![tset](https://cloud.githubusercontent.com/assets/1429384/10814030/000aca14-7e34-11e5-93a9-e6cd147e898d.png)

**Comment by dmitriid** [comment]
More information and Loïc's comments here: https://github.com/ninenines/erlang.mk/issues/384#issuecomment-156369194

**Comment by benoitc** [comment]
well it's more an issue in erlang.mk than anything. I will try to find a way to possibly change it. but not sure if a make file using rebar would fix it ;)

**Comment by dmitriid** [comment]
Thank you!
