### ISSUE TITLE
No build on windows

### ISSUE THREAD

**Issue by paulbombarde** [certifi/erlang-certifi#14]
Hello,

I'm trying to use httpoison on an elixir project (following chapter 13 of the "Programming Elixir" book). Under OSX, everything works fine, but not on windows machines as the certifi  module is not available.

After digging a little, I see that never unicode_util_compat nor certifi are built on windows. After a quick look, at the doc, adding a win32|win64 pre_hook for both projects made the trick once `make` is available on the target machine.

```
{"(win32|win64)", compile, "make -C uc_spec all"}
```

I hardly know what I'm doing here, but it would be nice if you could add a minimal support for windows.
Best regards,
Paul

PS: I opened a similar issue on unicode_util_compat

**Comment by benoitc** [comment]
thanks. This change looks good. Can you make a PR?

**Comment by ferd** [comment]
See #15

**Comment by benoitc** [comment]
@ferd @josevalim thanks for the PR just merged the version with parse transform which fix the issue above. I will update hackney later today.

**Comment by paulbombarde** [comment]
I confirm that the issue is now solved with the latest version. Thanks to all of you !
