### ISSUE TITLE
Compiling certifi on AWS failed

### ISSUE THREAD

**Issue by RalphMarks** [certifi/erlang-certifi#18]
Hi, I created an ubuntu instance on aws and when I try ti compile my project, the next error appears
==> certifi (compile)
sh: 1: exec: make: not found
ERROR: Command [compile] failed!
** (Mix) Could not compile dependency :certifi, "/home/ubuntu/.mix/rebar compile skip_deps=true deps_dir="/home/eiya/eiya-api/_build/dev/lib"" command failed.

You can recompile this dependency with "mix deps.compile certifi", update it with "mix deps.update certifi" or clean it with "mix deps.clean certifi"

Canonical, Ubuntu, 16.04 LTS, amd64 xenial image build on 2017-06-19

Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.5.0

certifi 1.2.1

**Comment by benoitc** [comment]
which version?

**Comment by RalphMarks** [comment]
The version is 1.2.1

**Comment by ericmj** [comment]
You need to install `make` or update to 2.0.0 which does not need `make`.
