### ISSUE TITLE
support rebar2

### ISSUE THREAD

**Issue by andreineculau** [certifi/erlang-certifi#29]
In an attempt to upgrade hackney, I have discovered that I cannot use rebar 2 anymore.
The issue is similar to https://github.com/benoitc/hackney/issues/509, just that it is not idna anymore, but certifi as mentioned also in https://github.com/benoitc/hackney/issues/509#issuecomment-401149674 (after the issue has been closed).

Thus a similar fix is needed here for parse_trans as in idna https://github.com/benoitc/erlang-idna/commit/f01533fa25ac32bcad07c9d0c183f1fede2bacda

**Comment by benoitc** [comment]
which error do you have ?

**Comment by andreineculau** [comment]
Same as in the comment https://github.com/benoitc/hackney/issues/509#issuecomment-401149674

**Comment by fenollp** [comment]
@andreineculau Is there no way to make you move to rebar3?

**Comment by andreineculau** [comment]
It is not just me the individual but all users of hackney (which @benoitc has said in a commit/issue that has to work with rebar2) and all users of my tool https://github.com/for-GET/katt

So all in all, no.
I know it's not a convenient situation, stemming from rebar3's backward-incompat, but if certifi is not to support rebar2, and then hackney neither, then 1. Would be good to state that in clear and 2. That there was a major semver bump when the incompat switch happens/ed

**Comment by benoitc** [comment]
it will need another rebar.config.script. i will take care on it.
