### ISSUE TITLE
Certifi not building with elixir

### ISSUE THREAD

**Issue by curtislinden** [certifi/erlang-certifi#3]
It appears that Cerfifi is not building when hackney 1.4.6 gets installed. 

It sounds like Elixir 1.2 will have rebar3 support - until then perhaps a similar solution to this would help?

https://github.com/benoitc/hackney/blob/master/rebar.config.script

Version bump is not essential. I'll drop back to older for now.

**Comment by benoitc** [comment]
it is fixed in latest hackney release

**Comment by curtislinden** [comment]
thank you kindly sir!


On Tue, Nov 24, 2015 at 4:20 PM, Benoit Chesneau <notifications@github.com>
wrote:

> it is fixed in latest hackney release
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/certifi/erlang-certifi/issues/3#issuecomment-159446170>
> .
>



-- 
Curtis J Schofield | Senior Systems Analyst | U2U
Skype robotarmymade | Second Life Curtis Linden | C 415.632.6001

Linden Lab | Makers of Shared Creative Spaces
